### ISSUE TITLE
Unexpected behaviour of `cpflow generate` command

### ISSUE THREAD

**Issue by zzaakiirr** [shakacode/control-plane-flow#218]
### Command

`cpflow generate` command's description states:
```
Description:
  Creates base Control Plane config and template files

  # Creates .controlplane directory with Control Plane config and other templates
  cpflow generate
```

### Expected behaviuor

User expects that invoking this command will create `.controlplane` directory with basic config and templates

### Actual behaviuor

Command fails with error:
```
ERROR: Can't find project config file at 'project_folder/.controlplane/controlplane.yml', please create it.
```

**Comment by borela** [comment]
@rafaelgomesxyz can we change the behavior of the command so that if the user doesn't provide the project config, it generates a default one?

**Comment by rafaelgomesxyz** [comment]
@borela This is definitely a bug, it should generate a config file by default. We even have a template for it: https://github.com/shakacode/control-plane-flow/blob/main/lib/generator_templates/controlplane.yml

**Comment by rafaelgomesxyz** [comment]
@zzaakiirr This is most likely because `VALIDATIONS = [].freeze` is missing from `Command::Generate`. I forgot to add it there when I added the `doctor` command.

**Comment by zzaakiirr** [comment]
> @zzaakiirr This is most likely because `VALIDATIONS = [].freeze` is missing from `Command::Generate`. I forgot to add it there when I added the `doctor` command.

You are right, adding `VALIDATIONS = [].freeze` to `Command::Generate` fixed the issue - now expected directory and files are created

@rafaelgomesxyz Can I open PR for this or will you work on this? We need to fix test for this too (`spec/command/generate_spec.rb:30`)

**Comment by rafaelgomesxyz** [comment]
Feel free to open it.
