### ISSUE TITLE
[USEFUL] `cpl doctor` Validate yaml file upon startup

### ISSUE THREAD

**Issue by ahangarha** [shakacode/control-plane-flow#99]
From #91 
---

- [ ] Workload names must match template file names and the workload name inside the templates
templates can contain multiple documents (working), but ONLY one workload with name-matching file name

**Comment by justin808** [comment]
Why is this true? 

> Workload names must match template file names

I don't think so.

**Comment by ahangarha** [comment]
@justin808 I agree with your new comment. I think the template's name can be anything suited to its content. It may match a workload name or not.

**Comment by ahangarha** [comment]
Can we list the factors to check for validation? Should we check types, or we leave it to cpln to handle it?
@justin808 @rafaelgomesxyz
